server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**
          filters:
            - StripPrefix=0
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**
          filters:
            - StripPrefix=0

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
