server:
#  port: 8761 #my machine
  port: 8080 #docker

spring:
  application:
    name: discovery-server

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
