server:
  port: 8080

spring:
  application:
    name: patient-service
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        security.protocol: PLAINTEXT
        spring.json.trusted.packages: "*"
  datasource:
    url: jdbc:postgresql://postgres-patient:5432/patient_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/clinic-realm

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
      webclient:
        enabled: true

info:
  app:
    name: Patient Service
    version: 1.0.0
    description: Service for managing patient records

management:
  info.env.enabled: true
  endpoints.web.exposure.include: health,info
