server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/clinic-realm
  datasource:
    url: jdbc:postgresql://postgres-patient:5432/patient_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: patient-service


info:
  app:
    name: Patient Service
    version: 1.0.0
    description: Service for managing patient records


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance-id: ${spring.cloud.client.ip-address}:${server.port}