server:
  port: 8084
  error:
    include-message: always
    include-stacktrace: always

spring:
  application:
    name: appointment-service
  main:
    banner-mode: "console"
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/clinic-realm

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: Appointment Service
    version: 1.0.0
    description: Service for managing patient appointments

logging:
  level:
    com.clinic.PatientClient: DEBUG
    feign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    doc-expansion: list
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: true
  pageable:
    default-sort: id,asc
