server:
  port: 8080

spring:
  application:
    name: appointment-service
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: appointment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        security.protocol: PLAINTEXT
        spring.json.trusted.packages: "*"
  datasource:
    url: jdbc:postgresql://postgres:5432/appointment_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/clinic-realm

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
      webclient:
        enabled: true

logging:
  level:
    com.clinic.PatientClient: DEBUG
    feign: DEBUG
