server:
#  port: 8084 #my machine
  port: 8080 #docker

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://postgres:5432/appointment_db #docker
#    url: jdbc:postgresql://localhost:5432/appointment_db #my machine
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8089/realms/clinic-realm #my machine
          issuer-uri: http://keycloak:8080/realms/clinic-realm #docker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
