server:
  port: 8080

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://postgres:5432/appointment_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/clinic-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
