server:
  port: 8084

spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/clinic-realm

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.clinic.PatientClient: DEBUG
    feign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG